CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(36) NOT NULL,
	`vehicleType` enum('new','used','refinance','unsure') NOT NULL,
	`estimatedPrice` int,
	`creditScore` enum('no_credit','below_500','500_549','550_599','600_649','650_699','700_plus') NOT NULL,
	`hasBankruptcy` boolean DEFAULT false,
	`hasRepossession` boolean DEFAULT false,
	`employmentStatus` enum('employed','self_employed','retired','disability','other'),
	`monthlyIncome` int,
	`firstName` varchar(64),
	`lastName` varchar(64),
	`email` varchar(320),
	`phone` varchar(20),
	`zipCode` varchar(10),
	`state` varchar(2),
	`trustedFormCertUrl` text,
	`ipAddress` varchar(45),
	`userAgent` text,
	`tcpaConsentText` text,
	`utmSource` varchar(128),
	`utmMedium` varchar(128),
	`utmCampaign` varchar(128),
	`landingPage` text,
	`abandonedAtStep` int,
	`status` enum('partial','submitted','matched','no_match','contacted') NOT NULL DEFAULT 'partial',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_token_unique` UNIQUE(`token`)
);
--> statement-breakpoint
CREATE TABLE `lender_offers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`lenderId` int NOT NULL,
	`pingAccepted` boolean NOT NULL DEFAULT false,
	`pingBid` decimal(8,2),
	`pingResponseMs` int,
	`pingRawResponse` json,
	`postSent` boolean NOT NULL DEFAULT false,
	`postAccepted` boolean NOT NULL DEFAULT false,
	`postRawResponse` json,
	`lenderName` varchar(128),
	`lenderLogoUrl` text,
	`aprMin` decimal(5,2),
	`aprMax` decimal(5,2),
	`estimatedMonthlyPayment` decimal(8,2),
	`termMonths` int,
	`approvalConfidence` enum('high','good','fair'),
	`isBestMatch` boolean NOT NULL DEFAULT false,
	`selectedByBorrower` boolean NOT NULL DEFAULT false,
	`selectedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lender_offers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lenders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`slug` varchar(64) NOT NULL,
	`logoUrl` text,
	`pingUrl` text,
	`postUrl` text,
	`apiKey` text,
	`pingFieldMap` json,
	`postFieldMap` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`priority` int NOT NULL DEFAULT 10,
	`maxBid` decimal(8,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lenders_id` PRIMARY KEY(`id`),
	CONSTRAINT `lenders_slug_unique` UNIQUE(`slug`)
);
