import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "Bad credit refinancing", "pros": ["Refinances existing high-rate loans", "Rate reduction guaranteed or we pay you $100", "Soft credit check to check rates", "Average savings of $87/month"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "RefiJet", "tagline": "Dedicated auto refinance specialist", "approvalRate": "88%", "minCreditScore": "500+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Refinancing", "pros": ["Refinance specialist", "Rate match", "Fast"], "featured": false, "ctaHref": "https://www.refijet.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "OpenRoad Lending", "tagline": "Subprime refinance lender", "approvalRate": "85%", "minCreditScore": "500+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Refinancing", "pros": ["Subprime refi", "Online process", "Fast decisions"], "featured": false, "ctaHref": "https://www.openroadlending.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "RateGenius", "tagline": "Multi-lender refinance marketplace", "approvalRate": "83%", "minCreditScore": "500+", "minIncome": "$2,000/mo", "downPayment": "$0", "bestFor": "Rate shopping", "pros": ["Multiple refi offers", "No application fee", "Fast"], "featured": false, "ctaHref": "https://www.rategenius.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "Capital One Auto Navigator", "tagline": "Bank-backed refinance program", "approvalRate": "80%", "minCreditScore": "500+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Trusted brand", "pros": ["Trusted brand", "Large network", "Soft pull"], "featured": false, "ctaHref": "https://www.capitalone.com/cars/prequalify", "ctaLabel": "Get Pre-Approved →"}];

export default function BestRefinanceBadCredit() {
  return (
    <BestOfPageTemplate
      seoTitle="Best Auto Refinance Loans for Bad Credit (2026) — Reviewed & Ranked"
      seoDescription="Find the best auto refinance options for bad credit in 2026. Lower your monthly payment or interest rate even with a score under 600."
      canonicalPath="/best-auto-refinance-bad-credit"
      ogImage="/manus-storage/best-car-loans-for-uber-lyft-drivers_og_7fa9b8fb.jpg"
      cityServiceSlug="bad-credit-auto-loans"
      title="Best Auto Refinance Loans for Bad Credit (2026)"
      subtitle="Already have a high-rate car loan? These lenders can refinance it — even with bad credit."
      intro="If you got a car loan at a high rate due to bad credit, refinancing after 12–18 months of on-time payments can save you hundreds per year. These lenders specialize in refinancing subprime borrowers."
      lenders={lenders}
      realStories={[{"name": "Carlos M.", "city": "Houston, TX", "creditScore": "561", "vehicle": "2018 Chevy Silverado", "downPayment": "N/A (refi)", "quote": "Got my original loan at 24% APR. After 14 months of on-time payments, refinanced at 14% APR. Saving $112/month. Wish I'd done it sooner."}]}
      faqs={[{"question": "Can I refinance my car loan with bad credit?", "answer": "Yes. Several lenders specialize in refinancing auto loans for borrowers with bad credit. If your credit score has improved since your original loan, or if interest rates have dropped, refinancing can lower your monthly payment and total interest paid."}, {"question": "When should I refinance my car loan?", "answer": "The best time to refinance is when: your credit score has improved by 50+ points since the original loan, interest rates have dropped, you are paying more than 18% APR on your current loan, or you need to lower your monthly payment. Most lenders recommend waiting at least 6-12 months after the original loan."}, {"question": "How much can I save by refinancing?", "answer": "Savings depend on the rate difference and remaining loan balance. Refinancing from 22% to 14% APR on a $12,000 balance with 36 months remaining saves approximately $1,440 in total interest and reduces monthly payments by about $40."}, {"question": "What credit score do I need to refinance?", "answer": "Refinance lenders in our network work with credit scores as low as 500. However, you will see the most meaningful rate reduction if your score has improved to at least 580-620 since your original loan."}, {"question": "Does refinancing hurt my credit score?", "answer": "Refinancing involves a hard inquiry, which may reduce your score by 2-5 points temporarily. However, if refinancing lowers your payment and you make consistent on-time payments, your score will recover and improve within 3-6 months."}, {"question": "What documents do I need to refinance?", "answer": "You will need: your current loan statement (showing payoff amount and lender), proof of income, vehicle information (VIN, mileage, year/make/model), and a valid driver's license. The process typically takes 1-3 business days."}, {"question": "Can I refinance if I owe more than the car is worth?", "answer": "Some lenders will refinance loans where you are slightly underwater (negative equity), but most prefer the loan-to-value ratio to be under 125%. If you owe significantly more than the car's value, you may need to pay down the balance first or wait until the equity improves."}]}
      relatedPages={[{"label": "Best Pre-Approved Car Loans", "href": "/best-pre-approved-car-loans-bad-credit"}, {"label": "Best Bad Credit Auto Loans", "href": "/best-bad-credit-auto-loans"}]}
      keyTakeaways={["Refinancing after 12–18 months of on-time payments can save $87+/month on average", "Your credit score improves significantly after 12 months of on-time payments", "The best time to refinance is when your score has improved 50+ points", "Soft credit checks let you shop rates without hurting your score"]}
    />
  );
}
