import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "Post-repossession approvals", "pros": ["Works with recent repossessions", "No waiting period", "Income-based approval", "All 50 states"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "Auto Credit Express", "tagline": "Repo specialist network", "approvalRate": "89%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Post-repo", "pros": ["Repo specialists", "Multiple lenders", "Fast"], "featured": false, "ctaHref": "https://www.autocreditexpress.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "JD Byrider", "tagline": "BHPH with repo acceptance", "approvalRate": "98%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$500", "bestFor": "Any repo", "pros": ["Accepts any repo", "Nationwide", "Guaranteed"], "featured": false, "ctaHref": "https://www.byrider.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "RoadLoans", "tagline": "Subprime lender accepting repos", "approvalRate": "85%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Recent repo", "pros": ["Accepts recent repos", "Fast decisions", "National"], "featured": false, "ctaHref": "https://www.roadloans.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "DriveTime", "tagline": "In-house financing post-repo", "approvalRate": "96%", "minCreditScore": "Any", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Any repo", "pros": ["No credit check", "Large inventory", "Guaranteed"], "featured": false, "ctaHref": "https://www.drivetime.com/", "ctaLabel": "Get Pre-Approved →"}];

export default function BestAfterRepossession() {
  return (
    <BestOfPageTemplate
      seoTitle="Best Auto Loans After Repossession of 2026 — Reviewed & Ranked"
      seoDescription="Find the best auto loans after a repossession in 2026. Get approved even with a recent repo on your record. Compare lenders with second-chance programs."
      canonicalPath="/best-auto-loans-after-repossession"
      cityServiceSlug="auto-loans-after-repossession"
      title="Best Auto Loans After Repossession (2026)"
      subtitle="A repossession on your record doesn't have to mean no car. These lenders work with repo borrowers every day."
      intro="A repossession is one of the hardest credit events to recover from, but it doesn't make getting a car loan impossible. The lenders on this list specifically work with borrowers who have a repo on their record."
      lenders={lenders}
      realStories={[{"name": "Marcus T.", "city": "Phoenix, AZ", "creditScore": "492", "vehicle": "2019 Honda Civic", "downPayment": "$500", "quote": "Had a repo from 2021 and thought no one would touch me. Complete Auto Loans matched me in 10 minutes and I drove home same day."}]}
      faqs={[{"question": "Can I get a car loan after a repossession?", "answer": "Yes. Lenders in our network specialize in post-repossession financing. A repossession stays on your credit report for 7 years, but it does not prevent you from getting a new loan. Approval is based on your current income and ability to make payments."}, {"question": "How long after a repossession can I get a car loan?", "answer": "You can apply for a new car loan immediately after a repossession — there is no mandatory waiting period. However, you must resolve any outstanding deficiency balance before most lenders will approve you."}, {"question": "What is a deficiency balance and do I need to pay it?", "answer": "A deficiency balance is the amount you still owe after the repossessed vehicle was sold at auction. For example, if you owed $8,000 and the car sold for $5,000, you owe a $3,000 deficiency. Most lenders require this to be settled or in a payment plan before approving a new loan."}, {"question": "What interest rate will I get after a repossession?", "answer": "Post-repossession auto loan rates typically range from 15.9% to 29.9% APR. The rate depends on how recently the repossession occurred, your current income, and your down payment. Rates improve after 12-18 months of on-time payments on the new loan."}, {"question": "How much down payment do I need after a repossession?", "answer": "Most lenders require $1,000 to $2,000 down after a repossession — higher than the standard $500 minimum. A larger down payment reduces the lender's risk and significantly improves your approval odds."}, {"question": "Will a new car loan help rebuild my credit after repossession?", "answer": "Yes. Every on-time payment on the new loan is reported to all three credit bureaus. Borrowers who make consistent payments typically see a 40-80 point improvement within 12 months, which can eventually allow refinancing at a lower rate."}, {"question": "Does applying affect my credit score?", "answer": "No. Complete Auto Loans uses a soft inquiry to match you with lenders, which does not affect your credit score. A hard inquiry only occurs when you formally accept a specific loan offer."}]}
      relatedPages={[{"label": "Best Second Chance Auto Loans", "href": "/best-second-chance-auto-loans"}, {"label": "Best Car Loans After Bankruptcy", "href": "/best-car-loans-after-bankruptcy"}]}
      keyTakeaways={["A repossession does not permanently disqualify you from getting a car loan", "BHPH dealers will approve you regardless of repo history", "Paying off the repo deficiency balance improves your rate significantly", "Repos have less impact on your score after 2–3 years"]}
    />
  );
}
