import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "Low income borrowers", "pros": ["Programs starting at $1,200/month income", "Payment plans from $150/month", "All income types accepted", "SSI, disability, and gig income OK"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "CarHop", "tagline": "BHPH with low income programs", "approvalRate": "95%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$0", "bestFor": "Low income", "pros": ["$1,200/mo minimum", "Flexible payments", "Credit building"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "JD Byrider", "tagline": "BHPH with flexible income requirements", "approvalRate": "97%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$500", "bestFor": "Low income", "pros": ["Low income OK", "Nationwide", "In-house"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "Auto Credit Express", "tagline": "Low income subprime network", "approvalRate": "88%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Low income", "pros": ["Low income specialists", "Multiple lenders", "Fast"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "DriveTime", "tagline": "In-house low income financing", "approvalRate": "94%", "minCreditScore": "Any", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Low income", "pros": ["Low income OK", "Large inventory", "Online"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}];

export default function BestLowIncome() {
  return (
    <BestOfPageTemplate
      seoTitle="Best Car Loans for Low Income Borrowers of 2026 — Reviewed"
      seoDescription="Compare the best car loans for low income borrowers in 2026. Get approved with income as low as $1,200/month. No minimum credit score required."
      canonicalPath="/best-car-loans-low-income"
      cityServiceSlug="bad-credit-auto-loans"
      title="Best Car Loans for Low Income Buyers (2026)"
      subtitle="Lower income doesn't mean no options. These lenders have programs designed for borrowers earning $1,200-$2,500/month."
      intro="Low income borrowers face a double challenge: bad credit and limited income. The lenders on this list have specifically designed programs for borrowers earning $1,200-$2,500/month, with payment structures that fit tighter budgets."
      lenders={lenders}
      realStories={[{"name": "Sandra L.", "city": "Houston, TX", "creditScore": "No Credit", "vehicle": "2018 Ford Focus", "downPayment": "$300", "quote": "I work part-time and get SSI. My income is only $1,400/month. Complete Auto Loans found me a lender that accepted all my income sources and got me approved."}]}
      faqs={[{"question": "Can I get a car loan on a low income?", "answer": "Yes. Many lenders in our network approve borrowers with monthly incomes as low as $1,500 from any verifiable source — employment, self-employment, disability, Social Security, or child support. Income stability matters more than the amount."}, {"question": "What is the minimum income required for a car loan?", "answer": "Most lenders require a minimum monthly income of $1,500 to $2,000. Some lenders will consider income as low as $1,200 per month for smaller loan amounts. The key is that the income is verifiable and consistent."}, {"question": "What types of income count toward a car loan?", "answer": "Lenders accept employment income, self-employment income, Social Security benefits, disability payments, child support, alimony, pension income, and rental income. You will need documentation — pay stubs, award letters, or bank statements showing consistent deposits."}, {"question": "What interest rate will I get with low income?", "answer": "Low income auto loan rates typically range from 10.9% to 24.9% APR depending on your credit score and down payment. A larger down payment is the most effective way to reduce your rate and monthly payment when income is limited."}, {"question": "How much car can I afford on a low income?", "answer": "A general rule is that your total monthly car payment (including insurance) should not exceed 15-20% of your monthly take-home pay. On a $1,800 per month income, this means a maximum payment of $270-$360."}, {"question": "Can I get a car loan with low income and bad credit?", "answer": "Yes, though it requires a larger down payment and may carry a higher interest rate. Lenders in our network specifically serve borrowers with both low income and bad credit. A $1,000+ down payment significantly improves approval odds in this situation."}, {"question": "Does applying affect my credit score?", "answer": "No. Complete Auto Loans uses a soft inquiry to match you with lenders, which does not affect your credit score. A hard inquiry only occurs when you formally accept a specific loan offer."}]}
      relatedPages={[{"label": "Best Buy Here Pay Here Dealerships", "href": "/best-buy-here-pay-here-dealerships"}, {"label": "Best No Money Down Car Loans", "href": "/best-no-money-down-car-loans"}]}
      keyTakeaways={["SSI, disability, and gig income all count toward the income requirement", "$1,200/month is the typical minimum income threshold", "BHPH dealers have the most flexible income requirements", "Payments as low as $150/month are available on some programs"]}
    />
  );
}
