import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "All BHPH situations", "pros": ["Connects you with vetted BHPH dealers", "No minimum credit score", "In-house financing guaranteed", "Local dealers in all 50 states"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "JD Byrider", "tagline": "National BHPH chain with 150+ locations", "approvalRate": "99%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$500", "bestFor": "Deep subprime", "pros": ["Guaranteed approval", "Service contracts included", "Nationwide locations"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "DriveTime", "tagline": "Used car dealer with in-house financing", "approvalRate": "98%", "minCreditScore": "Any", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "No credit", "pros": ["Large inventory", "Online pre-approval", "Multiple locations"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "CarHop", "tagline": "BHPH with credit building focus", "approvalRate": "97%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$0", "bestFor": "Credit building", "pros": ["Reports to credit bureaus", "No credit needed", "Flexible payments"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "Byrider", "tagline": "Regional BHPH with service plans", "approvalRate": "96%", "minCreditScore": "Any", "minIncome": "$1,000/mo", "downPayment": "$300", "bestFor": "Reliability focus", "pros": ["Vehicle inspections", "Warranty included", "Payment flexibility"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}];

export default function BestBuyHerePayHere() {
  return (
    <BestOfPageTemplate
      title="Best Buy Here Pay Here Dealerships of 2026"
      subtitle="BHPH dealerships offer in-house financing with no bank required — ideal for deep subprime borrowers who can't qualify anywhere else."
      intro="Buy Here Pay Here dealerships act as both the seller and the lender, which means they can approve borrowers that banks and traditional lenders won't touch. The trade-off is typically higher interest rates and a smaller vehicle selection."
      lenders={lenders}
      realStories={[{"name": "Kevin D.", "city": "Detroit, MI", "creditScore": "380", "vehicle": "2017 Chevy Malibu", "downPayment": "$500", "quote": "380 credit score, two collections, couldn't get approved anywhere. BHPH was the only option and Complete Auto Loans helped me find a reputable one."}, {"name": "Sandra L.", "city": "Houston, TX", "creditScore": "No Credit", "vehicle": "2018 Ford Focus", "downPayment": "$300", "quote": "Just moved to the US, no credit history at all. BHPH was the only path and it worked perfectly."}]}
      faqs={[{"question": "Is Buy Here Pay Here a good idea?", "answer": "BHPH is a good option when you have no other path to approval. The rates are higher, but it gets you into a vehicle and can help rebuild your credit if the dealer reports payments."}, {"question": "Do BHPH dealerships report to credit bureaus?", "answer": "Not all of them do. Always ask before signing. Dealers that report to Equifax, Experian, and TransUnion are significantly more valuable for credit rebuilding."}, {"question": "What down payment do I need for BHPH?", "answer": "Most BHPH dealers require $300–$1,000 down. Some offer $0 down but charge higher rates. The down payment is often negotiable."}]}
      relatedPages={[{"label": "Best Bad Credit Auto Loans", "href": "/best-bad-credit-auto-loans"}, {"label": "Best No Money Down Car Loans", "href": "/best-no-money-down-car-loans"}, {"label": "Best Second Chance Auto Loans", "href": "/best-second-chance-auto-loans"}]}
      keyTakeaways={["BHPH dealers approve borrowers with any credit score, including 300 and below", "Look for dealers that report payments to all three credit bureaus", "Rates are higher (18–29% APR) but the approval is nearly guaranteed", "A $500 down payment is the typical minimum"]}
    />
  );
}
