import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "ITIN borrowers", "pros": ["Accepts ITIN in place of SSN", "No citizenship required", "Income-based approval", "All 50 states"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "JD Byrider", "tagline": "BHPH accepting ITIN", "approvalRate": "97%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$500", "bestFor": "ITIN holders", "pros": ["Accepts ITIN", "Nationwide", "In-house financing"], "featured": false, "ctaHref": "https://www.byrider.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "DriveTime", "tagline": "In-house ITIN financing", "approvalRate": "95%", "minCreditScore": "Any", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "ITIN holders", "pros": ["ITIN accepted", "Large inventory", "Online process"], "featured": false, "ctaHref": "https://www.drivetime.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "Local BHPH Dealers", "tagline": "Local dealers with ITIN programs", "approvalRate": "93%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$500", "bestFor": "ITIN holders", "pros": ["Local relationships", "Flexible terms", "Community focused"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "CarHop", "tagline": "BHPH with ITIN acceptance", "approvalRate": "94%", "minCreditScore": "Any", "minIncome": "$1,200/mo", "downPayment": "$0", "bestFor": "ITIN holders", "pros": ["ITIN accepted", "Reports to bureaus", "Flexible"], "featured": false, "ctaHref": "https://www.carhop.com/apply-for-auto-financing-online/", "ctaLabel": "Get Pre-Approved →"}];

export default function BestITINLoans() {
  return (
    <BestOfPageTemplate
      seoTitle="Best ITIN Auto Loans of 2026 — Reviewed & Ranked"
      seoDescription="Compare the best ITIN auto loans of 2026. Get approved without a Social Security number using your Individual Taxpayer Identification Number."
      canonicalPath="/best-itin-auto-loans"
      ogImage="/images/best-itin-auto-loans_og_9d547952.jpg"
      cityServiceSlug="bad-credit-auto-loans"
      title="Best ITIN Auto Loans of 2026"
      subtitle="Don't have a Social Security number? These lenders accept ITIN numbers and approve borrowers without SSNs."
      intro="ITIN (Individual Taxpayer Identification Number) auto loans allow non-citizens and undocumented immigrants to finance a vehicle using their ITIN instead of a Social Security number. This is a growing and underserved market."
      lenders={lenders}
      realStories={[{"name": "Rosa V.", "city": "San Antonio, TX", "creditScore": "ITIN", "vehicle": "2021 Chevy Equinox", "downPayment": "$800", "quote": "I don't have a Social Security number but I have an ITIN and steady income. Complete Auto Loans was the only site that had options for me."}]}
      faqs={[{"question": "Can I get a car loan with an ITIN instead of a Social Security number?", "answer": "Yes. Several lenders in our network accept Individual Taxpayer Identification Numbers (ITINs) in place of Social Security numbers. These lenders specialize in serving immigrants, non-residents, and others who are not eligible for an SSN."}, {"question": "What documents do I need for an ITIN auto loan?", "answer": "Typically required: your ITIN card or IRS letter, a valid foreign passport or state ID, proof of income (pay stubs or bank statements), proof of residence (utility bill or lease), and a down payment. Requirements vary by lender."}, {"question": "What credit score do I need for an ITIN car loan?", "answer": "Many ITIN lenders do not require a U.S. credit history at all. They evaluate your income, employment stability, and down payment. If you have a credit history in your home country, some lenders will consider it."}, {"question": "What interest rate will I get with an ITIN?", "answer": "ITIN auto loan rates typically range from 10.9% to 24.9% APR. The rate depends on your income, down payment, and whether you have any U.S. credit history. A larger down payment is the most effective way to secure a lower rate."}, {"question": "How much down payment do I need for an ITIN loan?", "answer": "Most ITIN lenders require a down payment of 10-20% of the vehicle price, or a minimum of $1,000. A larger down payment reduces the lender's risk and improves your approval odds significantly."}, {"question": "Can an ITIN car loan help me build U.S. credit?", "answer": "Yes. Lenders who report to U.S. credit bureaus will help you establish a U.S. credit history with every on-time payment. This is one of the most effective ways for new arrivals to build a U.S. credit profile."}, {"question": "Is it safe to apply for a car loan with my ITIN?", "answer": "Yes. Your ITIN is a tax identification number issued by the IRS and is a legitimate form of identification for financial transactions. Reputable lenders handle ITIN information with the same security standards as Social Security numbers."}]}
      relatedPages={[{"label": "Best No Credit Check Car Loans", "href": "/best-no-credit-check-car-loans"}, {"label": "Best Buy Here Pay Here Dealerships", "href": "/best-buy-here-pay-here-dealerships"}]}
      keyTakeaways={["ITIN auto loans are available from BHPH dealers and some subprime lenders", "You need your ITIN letter, valid ID, proof of income, and proof of residence", "BHPH dealers are the most accessible option for ITIN borrowers", "This is a growing and underserved market with limited competition"]}
    />
  );
}
