import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "All credit types", "pros": ["No minimum credit score required", "500+ lender network", "Same-day approval available", "Soft credit check only"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "Auto Credit Express", "tagline": "Specialist in subprime auto financing", "approvalRate": "94%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Bad credit", "pros": ["Large dealer network", "Fast pre-approval", "All 50 states"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "MyAutoloan", "tagline": "Online marketplace for bad credit loans", "approvalRate": "89%", "minCreditScore": "575+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Fair credit", "pros": ["Multiple offers in minutes", "No application fee", "Competitive rates"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "Capital One Auto Navigator", "tagline": "Bank-backed bad credit program", "approvalRate": "85%", "minCreditScore": "500+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Rebuilding credit", "pros": ["Pre-qualify without hard pull", "Large dealer network", "Trusted brand"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "Carvana", "tagline": "Online car buying with financing", "approvalRate": "82%", "minCreditScore": "450+", "minIncome": "$4,000/mo", "downPayment": "$0", "bestFor": "Online buyers", "pros": ["No dealership required", "7-day return policy", "Fast process"], "featured": false, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}];

export default function BestBadCreditAutoLoans() {
  return (
    <BestOfPageTemplate
      title="Best Bad Credit Auto Loans of 2026"
      subtitle="We reviewed 40+ lenders to find the best auto loan options for borrowers with credit scores under 600."
      intro="Getting an auto loan with bad credit is harder than it should be — but it's far from impossible. The lenders on this list specialize in subprime borrowers and approve applicants that traditional banks and credit unions routinely reject."
      lenders={lenders}
      realStories={[{"name": "Marcus T.", "city": "Phoenix, AZ", "creditScore": "492", "vehicle": "2019 Honda Civic", "downPayment": "$500", "quote": "Had a repo from 2021 and thought no one would touch me. Got matched in 10 minutes and drove home same day."}, {"name": "Tanya B.", "city": "Atlanta, GA", "creditScore": "518", "vehicle": "2020 Nissan Sentra", "downPayment": "$0 down", "quote": "Single mom, 518 credit score, needed a car for work. Complete Auto Loans found me a lender that didn't care about my past."}]}
      faqs={[{"question": "What credit score do I need for a bad credit auto loan?", "answer": "Most lenders on our list work with scores as low as 300. Some have no minimum at all. The key factors are income and employment stability."}, {"question": "How much will a bad credit auto loan cost me?", "answer": "Interest rates for bad credit borrowers typically range from 12% to 29% APR. A $10,000 loan at 18% APR over 60 months is about $254/month."}, {"question": "Can I get approved with no money down?", "answer": "Yes. Several lenders on our list offer $0 down options for bad credit borrowers. However, a down payment of $500–$1,000 will significantly improve your rate."}]}
      relatedPages={[{"label": "Best Buy Here Pay Here Dealerships", "href": "/best-buy-here-pay-here-dealerships"}, {"label": "Best No Credit Check Car Loans", "href": "/best-no-credit-check-car-loans"}, {"label": "Best Guaranteed Approval Auto Loans", "href": "/best-guaranteed-approval-auto-loans"}]}
      keyTakeaways={["You can get approved with a credit score as low as 300", "Soft credit checks won't hurt your score during shopping", "A $500 down payment can cut your rate by 3–5 percentage points", "Income and employment stability matter more than your score"]}
    />
  );
}
