import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "All credit types", "pros": ["No minimum credit score required", "500+ lender network", "Same-day approval available", "Soft credit check only"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "Auto Credit Express", "tagline": "Specialist in subprime auto financing", "approvalRate": "94%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Bad credit", "pros": ["Large dealer network", "Fast pre-approval", "All 50 states"], "featured": false, "ctaHref": "https://www.autocreditexpress.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "MyAutoloan", "tagline": "Online marketplace for bad credit loans", "approvalRate": "89%", "minCreditScore": "575+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Fair credit", "pros": ["Multiple offers in minutes", "No application fee", "Competitive rates"], "featured": false, "ctaHref": "https://www.myautoloan.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "Capital One Auto Navigator", "tagline": "Bank-backed bad credit program", "approvalRate": "85%", "minCreditScore": "500+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Rebuilding credit", "pros": ["Pre-qualify without hard pull", "Large dealer network", "Trusted brand"], "featured": false, "ctaHref": "https://www.capitalone.com/cars/prequalify", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "Carvana", "tagline": "Online car buying with financing", "approvalRate": "82%", "minCreditScore": "450+", "minIncome": "$4,000/mo", "downPayment": "$0", "bestFor": "Online buyers", "pros": ["No dealership required", "7-day return policy", "Fast process"], "featured": false, "ctaHref": "https://www.carvana.com/financing", "ctaLabel": "Get Pre-Approved →"}];

export default function BestBadCreditAutoLoans() {
  return (
    <BestOfPageTemplate
      seoTitle="Best Bad Credit Auto Loans of 2026 — Reviewed & Ranked"
      seoDescription="Compare the best bad credit auto loans of 2026. We reviewed 40+ lenders to find options for scores under 600. No minimum credit score required."
      canonicalPath="/best-bad-credit-auto-loans"
      cityServiceSlug="bad-credit-auto-loans"
      title="Best Bad Credit Auto Loans of 2026"
      subtitle="We reviewed 40+ lenders to find the best auto loan options for borrowers with credit scores under 600."
      intro="Getting an auto loan with bad credit is harder than it should be — but it's far from impossible. The lenders on this list specialize in subprime borrowers and approve applicants that traditional banks and credit unions routinely reject."
      lenders={lenders}
      realStories={[{"name": "Marcus T.", "city": "Phoenix, AZ", "creditScore": "492", "vehicle": "2019 Honda Civic", "downPayment": "$500", "quote": "Had a repo from 2021 and thought no one would touch me. Got matched in 10 minutes and drove home same day."}, {"name": "Tanya B.", "city": "Atlanta, GA", "creditScore": "518", "vehicle": "2020 Nissan Sentra", "downPayment": "$0 down", "quote": "Single mom, 518 credit score, needed a car for work. Complete Auto Loans found me a lender that didn't care about my past."}]}
      faqs={[{"question": "Can I get a car loan with bad credit?", "answer": "Yes. Lenders in our network approve borrowers with credit scores as low as 300. Approval is primarily based on your income and ability to make monthly payments, not your credit score alone. Most applicants receive a decision within 2 minutes."}, {"question": "What credit score do I need to get a car loan?", "answer": "Most traditional lenders require a 600+ credit score. However, bad credit auto lenders in our network approve borrowers starting at 300. The lower your score, the higher your interest rate — but approval is still possible with steady income."}, {"question": "How much will a bad credit car loan cost per month?", "answer": "Monthly payments depend on the loan amount, interest rate, and term. For a $10,000 loan at 18% APR over 60 months, expect roughly $254/month. A larger down payment reduces both your monthly cost and total interest paid."}, {"question": "What interest rate can I expect with bad credit?", "answer": "Bad credit auto loan rates typically range from 10.9% to 29.9% APR depending on your credit score, income, and the lender. Borrowers with scores below 500 typically see rates of 20-29.9%. Improving your score by even 50 points before applying can meaningfully lower your rate."}, {"question": "Will applying hurt my credit score?", "answer": "No. Complete Auto Loans uses a soft credit inquiry to match you with lenders, which does not affect your credit score. Only when you formally accept a loan offer will a hard inquiry be made — and that typically reduces your score by fewer than 5 points."}, {"question": "How much down payment do I need?", "answer": "Most bad credit lenders require between $500 and $1,000 down. Some no-money-down programs are available for borrowers with steady income. A larger down payment reduces your monthly payment, lowers your interest rate, and improves your approval odds."}, {"question": "How fast can I get approved?", "answer": "Most borrowers receive a lender match within 2 minutes of completing the application. Same-day approval and same-day vehicle pickup are common through our network. Funding typically occurs within 24 hours of signing."}, {"question": "Can a bad credit car loan help rebuild my credit?", "answer": "Yes. Every on-time payment is reported to Experian, Equifax, and TransUnion. Borrowers who make consistent payments typically see a 40-80 point improvement in their credit score within 12 months."}]}
      relatedPages={[{"label": "Best Buy Here Pay Here Dealerships", "href": "/best-buy-here-pay-here-dealerships"}, {"label": "Best No Credit Check Car Loans", "href": "/best-no-credit-check-car-loans"}, {"label": "Best Guaranteed Approval Auto Loans", "href": "/best-guaranteed-approval-auto-loans"}]}
      keyTakeaways={["You can get approved with a credit score as low as 300", "Soft credit checks won't hurt your score during shopping", "A $500 down payment can cut your rate by 3–5 percentage points", "Income and employment stability matter more than your score"]}
    />
  );
}
