import BestOfPageTemplate from "../components/BestOfPageTemplate";
import type { Lender } from "../components/LenderCard";

const lenders: Lender[] = [{"rank": 1, "name": "Complete Auto Loans", "tagline": "Our top-rated network for bad credit borrowers", "approvalRate": "98%", "minCreditScore": "Any Score", "minIncome": "$1,200/mo", "downPayment": "$0–$500", "bestFor": "Post-bankruptcy approvals", "pros": ["Approves Chapter 7 and Chapter 13", "No waiting period required", "Discharge not required to apply", "Rebuilds credit with on-time payments"], "featured": true, "ctaHref": "/apply", "ctaLabel": "Get Pre-Approved →"}, {"rank": 2, "name": "Auto Credit Express", "tagline": "Bankruptcy specialist network", "approvalRate": "91%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Post-bankruptcy", "pros": ["Bankruptcy specialists", "No waiting period", "Multiple lenders"], "featured": false, "ctaHref": "https://www.autocreditexpress.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 3, "name": "RoadLoans", "tagline": "Santander-backed bankruptcy lender", "approvalRate": "88%", "minCreditScore": "300+", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Bankruptcy", "pros": ["Accepts open bankruptcy", "Fast decisions", "National"], "featured": false, "ctaHref": "https://www.roadloans.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 4, "name": "DriveTime", "tagline": "In-house financing post-bankruptcy", "approvalRate": "96%", "minCreditScore": "Any", "minIncome": "$1,500/mo", "downPayment": "$500", "bestFor": "Any bankruptcy", "pros": ["No credit check", "Large inventory", "Guaranteed"], "featured": false, "ctaHref": "https://www.drivetime.com/", "ctaLabel": "Get Pre-Approved →"}, {"rank": 5, "name": "Capital One Auto Navigator", "tagline": "Bank with bankruptcy program", "approvalRate": "82%", "minCreditScore": "500+", "minIncome": "$1,800/mo", "downPayment": "$0", "bestFor": "Discharged BK", "pros": ["Trusted brand", "Post-discharge program", "Large network"], "featured": false, "ctaHref": "https://www.capitalone.com/cars/prequalify", "ctaLabel": "Get Pre-Approved →"}];

export default function BestAfterBankruptcy() {
  return (
    <BestOfPageTemplate
      seoTitle="Best Car Loans After Bankruptcy of 2026 — Reviewed & Ranked"
      seoDescription="Compare the best auto loans after bankruptcy in 2026. Get approved after Chapter 7 or Chapter 13. Lenders that work with discharged and active BK."
      canonicalPath="/best-car-loans-after-bankruptcy"
      cityServiceSlug="car-loans-after-bankruptcy"
      title="Best Car Loans After Bankruptcy (2026)"
      subtitle="Bankruptcy doesn't end your ability to get a car loan. These lenders specialize in post-bankruptcy financing."
      intro="Getting a car loan after bankruptcy is possible — and often easier than people expect. Lenders know that a bankruptcy discharge means your debt slate is clean and you legally can't file again for several years, which actually makes you a lower risk."
      lenders={lenders}
      realStories={[{"name": "David & Lisa M.", "city": "Chicago, IL", "creditScore": "538", "vehicle": "2018 Ford Explorer", "downPayment": "$1,000", "quote": "Chapter 7 bankruptcy discharged 8 months ago. We needed an SUV for our kids. Got approved for a rate we could actually afford."}]}
      faqs={[{"question": "Can I get a car loan after bankruptcy?", "answer": "Yes. Many lenders in our network specialize in post-bankruptcy auto financing. There is no mandatory waiting period — you can apply the day after a Chapter 7 discharge. Chapter 13 borrowers can apply during the repayment plan with trustee approval."}, {"question": "How soon after bankruptcy can I get a car loan?", "answer": "You can apply for a car loan immediately after a Chapter 7 discharge — there is no waiting period. For Chapter 13, you can apply during the repayment plan with court approval. Most lenders prefer to see at least 1-2 months of post-discharge history, but same-day approval is possible."}, {"question": "What interest rate will I get after bankruptcy?", "answer": "Post-bankruptcy auto loan rates typically range from 12.9% to 29.9% APR. The rate depends on how recently you filed, your current income, and your down payment. Rates improve significantly after 12-18 months of on-time payments on the new loan."}, {"question": "What do I need to qualify for a car loan after bankruptcy?", "answer": "The primary requirements are: proof of bankruptcy discharge (or trustee approval for Chapter 13), verifiable monthly income of at least $1,500, a valid driver's license, and a down payment of $500 or more. Credit score is not a disqualifying factor."}, {"question": "Will a car loan help rebuild my credit after bankruptcy?", "answer": "Yes — a post-bankruptcy auto loan is one of the most effective credit-rebuilding tools available. Every on-time payment is reported to all three bureaus. Borrowers typically see a 50-100 point improvement within 12-18 months of consistent payments."}, {"question": "How much down payment do I need after bankruptcy?", "answer": "Most post-bankruptcy lenders require $500 to $1,500 down. A larger down payment (10-20% of the vehicle price) significantly improves approval odds and results in a lower interest rate."}, {"question": "Does applying for a car loan after bankruptcy hurt my credit?", "answer": "No. Complete Auto Loans uses a soft inquiry to match you with lenders, which does not affect your credit score. A hard inquiry only occurs when you formally accept a specific loan offer — and that impact is minimal (fewer than 5 points)."}]}
      relatedPages={[{"label": "Best Second Chance Auto Loans", "href": "/best-second-chance-auto-loans"}, {"label": "Best Auto Loans After Repossession", "href": "/best-auto-loans-after-repossession"}]}
      keyTakeaways={["You can apply for a car loan immediately after bankruptcy, even before discharge", "A bankruptcy discharge can actually make you less risky to some lenders", "Expect rates of 18–29% APR, but plan to refinance after 12–18 months", "BHPH dealers will approve you regardless of bankruptcy status"]}
    />
  );
}
